import = ["~/.config/alacritty/themes/themes/solarized_osaka.toml"]
# import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]

[window]
dimensions = { columns = 90, lines = 30 }
padding.x = 8
padding.y = 8
decorations = "Buttonless"
opacity = 1
blur = true

[font]
offset = { x = 1, y = 0 }
# normal = { family = "Menlo", style = "Regular" }
# normal = { family = "Menlo For Powerline", style = "Regular" }
# normal = { family = "Hack Nerd Font", style = "Regular" }
normal = { family = "Liga SFMono Nerd Font", style = "Medium" }
# normal = { family = "JetbrainsMono Nerd Font", style = "Regular" }
# normal = { family = "Geist Mono", style = "Regular" }
# normal = { family = "MonoLisa Nerd Font Mono", style = "Regular" }
# normal = { family = "CaskaydiaCove Nerd Font", style = "Regular" }
size = 15

[mouse]
hide_when_typing = true
