"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](rose)\
$os\
$username\
[](bg:gold fg:rose)\
$directory\
[](bg:foam fg:gold)\
$git_branch\
$git_status\
[](fg:foam bg:pine)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:pine bg:iris)\
[](fg:iris bg:surface)\
[ ](fg:surface)\
$line_break\
$character"""

palette = 'rose_pine'

[os]
disabled = false
style = "bg:rose fg:base"

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:rose fg:base"
style_root = "bg:rose fg:base"
format = '[ $user]($style)'

[directory]
style = "bg:gold fg:base"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:foam"
format = '[[ $symbol $branch ](fg:base bg:foam)]($style)'

[git_status]
style = "bg:foam"
format = '[[($all_status$ahead_behind )](fg:base bg:foam)]($style)'

# --- LANG TOOLS (pine background) --- #
[nodejs]
symbol = ""
style = "bg:pine"
format = '[[ $symbol( $version) ](fg:base bg:pine)]($style)'

[c]
symbol = " "
style = "bg:pine"
format = '[[ $symbol( $version) ](fg:base bg:pine)]($style)'

[rust]
symbol = ""
style = "bg:pine"
format = '[[ $symbol( $version) ](fg:base bg:pine)]($style)'

[golang]
symbol = ""
style = "bg:pine"
format = '[[ $symbol( $version) ](fg:base bg:pine)]($style)'

[php]
symbol = ""
style = "bg:pine"
format = '[[ $symbol( $version) ](fg:base bg:pine)]($style)'

[java]
symbol = " "
style = "bg:pine"
format = '[[ $symbol( $version) ](fg:base bg:pine)]($style)'

[kotlin]
symbol = ""
style = "bg:pine"
format = '[[ $symbol( $version) ](fg:base bg:pine)]($style)'

[haskell]
symbol = ""
style = "bg:pine"
format = '[[ $symbol( $version) ](fg:base bg:pine)]($style)'

[python]
symbol = ""
style = "bg:pine"
format = '[[ $symbol( $version)(\(#$virtualenv\)) ](fg:base bg:pine)]($style)'

[cmd_duration]
show_milliseconds = true
format = " in $duration "
style = "bg:iris"
disabled = false

[time]
disabled = false
time_format = "%R"
style = "bg:surface"
format = "[  $time ]($style)"

[line_break]
disabled = true

[character]
disabled = false
success_symbol = '[❯](bold fg:foam)'
error_symbol = '[❯](bold fg:love)'
vimcmd_symbol = '[❮](bold fg:foam)'

# ---- ROSE PINE PALETTE ---- #
[palettes.rose_pine]
base     = "#191724"
surface  = "#1f1d2e"
overlay  = "#26233a"
muted    = "#6e6a86"
subtle   = "#908caa"
text     = "#e0def4"
love     = "#eb6f92"
gold     = "#f6c177"
rose     = "#ebbcba"
pine     = "#31748f"
foam     = "#9ccfd8"
iris     = "#c4a7e7"
