sbar.bar({
	topmost = "window",
	height = 32,
	color = 0x00000000,
	border_width = 0,
	shadow = false,
	position = "top",
	sticky = true,
	padding_right = 8,
	padding_left = 8,
	y_offset = 6,
	margin = 8,
	blur_radius = 0,
	corner_radius = 0,
})
