set -g @tmux-dotbar-position top

# Rosé Pine theme
set -g @tmux-dotbar-bg "#000000"
set -g @tmux-dotbar-fg "#6e6a86"
set -g @tmux-dotbar-fg-current "#e0def4"
set -g @tmux-dotbar-fg-session "#908caa"
set -g @tmux-dotbar-fg-prefix "#eb6f92"
