set -g @minimal-tmux-fg "#000000"
set -g @minimal-tmux-bg "#f6c177" # Gold
# set -g @minimal-tmux-bg "#eb6f92" # Love


set -g @minimal-tmux-status "top"
set -g @minimal-tmux-use-arrow true
set -g @minimal-tmux-right-arrow ""
set -g @minimal-tmux-left-arrow ""
