# Start tmux session index from 1
set -g base-index 1
setw -g pane-base-index 1

# Set the default terminal to support 256 colors and true color
# set -g default-terminal "screen-256color"
# set -ga terminal-overrides ",xterm-256color:RGB"
# set default-terminal colors to display default terminal colors
set -g default-terminal "xterm-256color"
# set-option -ga terminal-overrides ',xterm-256color:Tc
# Proper colors
set-option -sa terminal-features ',xterm-256color:RGB'
# Undercurl
set-option -g default-terminal "tmux-256color"
set-option -ga terminal-features ",xterm-256color:usstyle"

# Enable mouse support for easier navigation
set -g mouse on
set -g renumber-windows on

# Set prefix to Ctrl-a for easier access
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Reload config file with Prefix + r
bind r source-file ~/.config/tmux/tmux.conf \; display "✨ Config reloaded! ✨"

# Pane switching with Alt + arrow keys without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Split panes with | and -
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# skip "kill-pane 1? (y/n)" prompt
bind-key x kill-pane
# don't exit from tmux when closing a session
set -g detach-on-destroy off

# Bind uppercase 'T' to clock-mode instead of 't'
unbind t
bind T clock-mode

# Appearance
set-option -g status-position top 

# Tmux session management using sesh + fzf
bind-key "t" run-shell "sesh connect \"$(
  sesh list --icons | fzf-tmux -p 80%,70% \
    --no-sort --ansi --border-label ' sesh ' --prompt '⚡  ' \
    --header '  ^a all ^t tmux ^g configs ^x zoxide ^d tmux kill ^f find' \
    --bind 'tab:down,btab:up' \
    --bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list --icons)' \
    --bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list -t --icons)' \
    --bind 'ctrl-g:change-prompt(⚙️  )+reload(sesh list -c --icons)' \
    --bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -z --icons)' \
    --bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
    --bind 'ctrl-d:execute(tmux kill-session -t {2..})+change-prompt(⚡  )+reload(sesh list --icons)' \
    --preview-window 'right:55%' \
    --preview 'sesh preview {}'
)\""

# Initialize Tmux Plugin Manager
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'vaaleyard/tmux-dotbar'
source-file ~/.config/tmux/conf.d/dotbar.conf
set-option -g status-left-length 100

# Initialize TPM (must be at the bottom)
run '~/.config/tmux/plugins/tpm/tpm'
